version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  celeryworker:
    build:
      context: .
    command: celery -A server.tasks.celery_notification_tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped

  celerybeat:
    build:
      context: .
    command: celery -A server.tasks.celery_notification_tasks.celery_app beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
